apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: www.thevouch-msc-fyp.shop
      http:
        paths:
          - path: /api/payments/?(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-srv
                port:
                  number: 3000
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/vouchers/?(.*)
            pathType: Prefix
            backend:
              service:
                name: vouchers-srv
                port:
                  number: 3000
          - path: /api/orders/?(.*)
            pathType: Prefix
            backend:
              service:
                name: orders-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   annotations:
#     # service.beta.kubernetes.io/do-loadbalancer-certificate-id: '1234-5678-9012-3456'
#     # service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
#     # Uncomment once hello.example.com points to the external IP address of the DO load-balancer
#     service.beta.kubernetes.io/do-loadbalancer-hostname: 'www.thevouch-msc-fyp.shop'
#   labels:
#     helm.sh/chart: ingress-nginx-4.2.5
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/instance: ingress-nginx
#     app.kubernetes.io/version: 1.4.0
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/component: controller
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# spec:
#   type: LoadBalancer
#   externalTrafficPolicy: Local
#   ports:
#     - name: http
#       port: 80
#       protocol: TCP
#       targetPort: http
#     - name: https
#       port: 443
#       protocol: TCP
#       targetPort: https
#   selector:
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/instance: ingress-nginx
#     app.kubernetes.io/component: controller
