name: deploy-vouchers

on:
  push:
    branches:
      - main
    paths:
      - 'vouchers/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd vouchers && docker build -t dsprouts/vouchers .
      - run: docker push dsprouts/vouchers
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save thevouch
      - run: kubectl rollout restart deployment vouchers-depl
